# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'TrivagoCaseStudy' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrivagoCaseStudy
  pod 'Alamofire', '~> 3.0'
  pod 'AlamofireImage', '~> 2.0'
  pod 'PKHUD'

end
